### ISSUE TITLE
Propagate search query as URL param

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/sampler#47]
It seems to be useful to be able to share search results to someone

**Comment by GlebDurygin** [comment]
In the **Sampler** application, the `Menu` and the `WorkArea` are two independent components, the content of which often does not match. For example, we can enter a search query - “Button”, but the fragment associated with the `Table` component will be opened in `WorkArea`. The content displayed in the `WorkArea` will not match the result of the search query.

As done in the documentation - the search results are displayed in `WorkArea` and after clicking on one of the links, the search results are erased from the URL parameters. In the **Sampler** application, we cannot do this, since the `Menu` and the `WorkArea` are completely independent from each other. When searching, the `WorkArea` does not update its content, only menu items are updated.

Therefore, there is no need to save the search results as a URL parameter, so as not to confuse users.
